project:
  type: website

website:
  title: "一木 | yimu"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/ifendo
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual
